1 module
js-tasks-ru/jsbasic-20201214_viktoriyakulko pull request #2
Opened 2020-12-18 00:17 UTC by ViktoriiaKulko

2020-12-18 00:56 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если имя корректное, то true
+ если содержит пробелы, то false
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для 'free xxxxx'
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-18 08:45 UTC, SinimaWath requested changes
Привет молодец! Давай поправим некоторые маленькие замечания.

2020-12-18 08:45 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str.slice(0, maxlength - 1) + '…';
Давай переделаем на шаблонные строки, которые я показываал на лекции ;)

2020-12-18 08:45 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  return str;
Не хватает отступа от if блока

2020-12-18 08:45 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let updatedStr = str.toLowerCase();
1) Это const, так как страка не изменяется.
2) Не самое понятное название переменной. Названии должно отражать, что она в себе хранит и для чего нужна. К примеру, `lowerCaseStr`,

2020-12-18 23:20 UTC, ViktoriiaKulko commented on 1-module/5-task/index.js
> +    return str.slice(0, maxlength - 1) + '…';
готово

2020-12-18 23:20 UTC, ViktoriiaKulko commented on 1-module/5-task/index.js
> +  return str;
готово

2020-12-18 23:20 UTC, ViktoriiaKulko commented on 1-module/4-task/index.js
> +  let updatedStr = str.toLowerCase();
готово

2020-12-18 23:45 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 3 равен 6 
+ факториал 1 равен 1
+ факториал 0 равен 1
```
```diff
Проверка на спам
+ дол��на возвращать true для 'free xxxxx'
+ должна возвращать true для '1XbeT now'
+ должна возвращать false для 'innocent rabbit'
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-19 01:01 UTC, SinimaWath approved these changes

2020-12-19 01:01 UTC, merged