2 module
js-tasks-ru/jsbasic-20201214_viktoriyakulko pull request #3
Opened 2020-12-21 21:48 UTC by ViktoriiaKulko

2020-12-21 22:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```
```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ объект с удалённым свойством - пустой
+ если у объекта есть хоть одно свойство, то он не пустой
```
```diff
Функция sumSalary(salaries)
+ должна игнорировать специальные числовые значения
+ должна игнорировать свойства других типов
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-22 15:43 UTC, SinimaWath requested changes

2020-12-22 15:43 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  for (let key in obj) {
Лучше давай использовать `const key`

2020-12-22 15:43 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    this.a = a;
Лучше явно обьявлять свойства обьекта, с значениями по-умолчанию. Давай добавим эти свойства на этапе инициализации

2020-12-22 21:05 UTC, ViktoriiaKulko commented on 2-module/3-task/index.js
> +    this.a = a;
готово

2020-12-22 21:05 UTC, ViktoriiaKulko commented on 2-module/2-task/index.js
> +  for (let key in obj) {
готово

2020-12-22 21:41 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
```
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```
```diff
Функция sumSalary(salaries)
+ должна складывать все зарплаты
+ должна игнорировать свойства других типов
+ должна игнорировать специальные числовые значения
+ должна возвращать 0 если нет свойств с зарплатами
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-22 21:53 UTC, SinimaWath approved these changes

2020-12-22 21:53 UTC, merged